{% set version = "v0.5.1" %}
{% set build = 2 %}

package:
  name: paraprobe
  version: {{ version }}

source:
  - url: https://gitlab.com/paraprobe/paraprobe-toolbox/-/archive/{{ version }}/paraprobe-toolbox-{{ version }}.tar.gz
    sha256: 2bb28cf6e82c82202f254058eb6d55433d391cf5ecce479b5d7774e70adb7ebe
    folder: paraprobe-toolbox
    patches:
      - paraprobe.patch
 
build:
  number: {{ build }}
  skip: true  # [not linux]
  #skip: True  # [osx]
  #skip: True  # [py<38] 

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"
  ignore_run_exports_from:
    - libaec
    # need to keep voro because it's a static lib
    # that (likely) ends up in the link interface
    # - voro
    - zlib

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - git
    - m4
    - libgomp      # [linux]
    - llvm-openmp  # [osx]

  host:
    - python
    - cython
    - setuptools
    - {{ mpi }}
    - gmp
    - mpfr
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - libboost-headers
    - eigen
    - voro
    - cgal
    - cgal-cpp
    - libaec
    - numpy
    - openssl
    - zlib
  run:
    - python
    - setuptools
    - numpy
    - h5py
    - gitpython
    - jupyterlab
    - jupyterlab-h5web
    - nodejs
    - scikit-learn
    - pandas
    - ase
    - radioactivedecay
    - ifes-apt-tc-data-modeling
    - hdbscan
    - sphinx
    - odfpy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    # relevant for pure python tools
    - paraprobe_utils
    - paraprobe_parmsetup
    - paraprobe_reporter
    - paraprobe_transcoder
    - paraprobe_clusterer
  commands:
    - paraprobe_ranger --help
    - paraprobe_selector --help
    - paraprobe_surfacer --help
    - paraprobe_distancer --help
    - paraprobe_tessellator --help
    - paraprobe_spatstat --help
    - paraprobe_nanochem --help
    - paraprobe_intersector --help

about:
  home: https://gitlab.com/paraprobe/paraprobe-toolbox
  summary: 'paraprobe-toolbox'
  license: GPL-3.0-only
  license_family: GPL
  license_file:
    - LICENSE
    - VORO_LICENSE
  doc_url: https://paraprobe-toolbox.readthedocs.io/en/main
  dev_url: https://gitlab.com/paraprobe/paraprobe-toolbox

extra:
  recipe-maintainers:
    - srmnitc
